Case Study
==========
Import data, fix na and col names
```{r}
pm0 = read.table('./CaseStudy/pm25_data/RD_501_88101_1999-0.txt', comment.char = '#', header=F, sep='|', na.strings="")
dim(pm0)
head(pm0)
cnames = readLines('./CaseStudy//pm25_data/RD_501_88101_1999-0.txt', 1)
cnames = strsplit(cnames, '|', fixed=T)
names(pm0) = make.names(cnames[[1]])  # NEW: make.names()
x0 = pm0$Sample.Value
class(x0)
str(x0)
summary(x0)
mean(is.na(x0))   # NEW: % of na values in vector

pm1 = read.table('./CaseStudy/pm25_data/RD_501_88101_2012-0.txt', comment.char = '#', header=F, sep='|', na.strings="")
dim(pm1)
names(pm1) = make.names(cnames[[1]])
head(pm1)
format(object.size(pm1), units='auto')
x1 = pm1$Sample.Value
str(x1)
summary(x0)
summary(x1)
mean(is.na(x1))
boxplot(x0,x1, outline=F) 
boxplot(log(x0), log(x1))
```

Fix negative values
```{r}
summary(x1)
negative = x1 < 0
sum(negative, na.rm=T)
mean(negative, na.rm=T)
dates = pm1$Date
str(dates)
dates = as.Date(as.character(dates), '%Y%m%d')  # NEW: as.Date() like ymd()
hist(dates, 'month')  # NEW: hist with date object
hist(dates[negative], 'month')
```

Monitor NY
```{r}
site0 = unique(subset(pm0, State.Code == 36, c(County.Code, Site.ID))) 
site1 = unique(subset(pm1, State.Code == 36, c(County.Code, Site.ID))) 

site0 = paste(site0[,1], site0[,2], sep='.')
site1 = paste(site1[,1], site1[,2], sep='.')
both = intersect(site0, site1)
pm0$county.site = with(pm0, paste(County.Code, Site.ID, sep='.'))
pm1$county.site = with(pm1, paste(County.Code, Site.ID, sep='.'))
cnt0 = subset(pm0, State.Code == 36 & county.site %in% both)
cnt1 = subset(pm1, State.Code == 36 & county.site %in% both)
sapply(split(cnt0, cnt0$county.site), nrow)
sapply(split(cnt1, cnt1$county.site), nrow)

pm0sub = subset(pm0, State.Code == 36 & County.Code == 63 & Site.ID == 2008)
pm1sub = subset(pm1, State.Code == 36 & County.Code == 63 & Site.ID == 2008)
dates1 = pm1sub$Date
x1sub = pm1sub$Sample.Value
plot(dates1, x1sub)
dates1 = as.Date(as.character(dates1), '%Y%m%d')
str(dates1)

dates0 = pm0sub$Date
x0sub = pm0sub$Sample.Value
dates0 = as.Date(as.character(dates0), '%Y%m%d')

# put multiple objects in range()
range(x0sub, x1sub, na.rm=T)

par(mfrow = c(1,2), mar=c(4,4,2,1))
plot(dates0, x0sub, pch=20, ylim=c(3,41)) 
abline(h=median(x0sub,na.rm=T))
plot(dates1, x1sub, pch=20, ylim=c(3,41))
abline(h=median(x1sub,na.rm=T))

mn0 = with(pm0, tapply(Sample.Value, State.Code, mean, na.rm=T))
str(mn0)
summary(mn0)

```


